Semon
Amyton0/mathStatisticsProject pull request #1
Opened 2024-05-10 12:47 UTC by semon24

2024-05-10 13:46 UTC, Cockamamie requested changes

2024-05-10 13:46 UTC, Cockamamie commented on Server/Data/Context.cs
> +            modelBuilder.Entity<Student>().HasKey(a => a.Id);
EF по имени поля 'Id' сам догадается, что это первичный ключ

2024-05-10 13:46 UTC, Cockamamie commented on Server/Models/Homework.cs
> +    [Table("homeWorks")]
EF должен догадаться до имени таблицы

2024-05-10 13:46 UTC, Cockamamie commented on Server/Program.cs
> +await f.addStudent(new Guid("5de4dd70-aeaa-4dee-807e-f7f8532755b8"), "Seааааmen", "Tereshenko", "Michaylovich", "ФТ-204");
вернуть, как было

2024-05-10 13:46 UTC, Cockamamie commented on Server/Repositories/Filter.cs
> +    public string?[] Groups { get; set; }
зачем nullable у массивов-то? Если query-параметр не был передан, то массив пустой и все
И лучше List<>

2024-05-10 13:46 UTC, Cockamamie commented on Server/Models/Homework.cs
> +        [Column]
Насчет энамов вот норм [статья](https://dev.to/karenpayneoregon/using-enum-with-ef-core-20go)

2024-05-10 13:46 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +            return new List<dynamic> { filteredStudents };
Никакого dynamic не должно быть

2024-05-10 13:46 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +            foreach (var studentHomeworks in JoinStudentHomeworksWithFilter())
А если фильтра по группам нет, зачем join делать?

2024-05-10 13:46 UTC, Cockamamie commented on Server/Models/Homework.cs
> +        public string WriteMessage
Для чего это?

2024-05-10 13:46 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +                foreach (var filterGroup in filter.Groups)
С учетом коммента про ненадобность nullable в списках: `if (filter.Groups.Any() && !filter.Groups.Contains(homework.Group)`
Аналогично другие фильтры по списку

2024-05-10 13:46 UTC, Cockamamie commented on Server/Models/Message.cs
> +        public string WriteMessage { get; set; }
Что это?

2024-05-10 13:46 UTC, Cockamamie commented on Server/Repositories/Filter.cs
> +namespace MathStatisticsProject.Repositories;
Фильтр будет в контроллере использоваться

2024-05-10 13:46 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +            context.Homeworks.Add(homework);
Асинхронно

2024-05-10 13:47 UTC, Cockamamie commented
Еще куча парашного кода, но все расписывать долго. Код стайл почитай

2024-05-10 14:10 UTC, semon24 commented on Server/Models/Message.cs
> +        public string WriteMessage { get; set; }
это до меня было, я не совсем понимаю зачем, ведь у нас в бд только content и writeMessage есть
а остальные ваще нигде не используются

2024-05-10 14:11 UTC, semon24 commented on Server/Data/Context.cs
> +            modelBuilder.Entity<Student>().HasKey(a => a.Id);
убрал

2024-05-10 14:12 UTC, semon24 commented on Server/Models/Homework.cs
> +    [Table("homeWorks")]
не совсем понимаю, что ты тут имеешь ввиду

2024-05-10 14:17 UTC, semon24 commented on Server/Program.cs
> +await f.addStudent(new Guid("5de4dd70-aeaa-4dee-807e-f7f8532755b8"), "Seааааmen", "Tereshenko", "Michaylovich", "ФТ-204");
вернул

2024-05-10 14:20 UTC, semon24 commented on Server/Repositories/Filter.cs
> +    public string?[] Groups { get; set; }
переделал

2024-05-10 14:23 UTC, semon24 commented on Server/Repositories/HomeworkRepository.cs
> +                foreach (var filterGroup in filter.Groups)
нам же все равно надо проверять его что оне пустой, ведь если пустой то значит выбрано все, а это нам подходит

2024-05-10 14:26 UTC, semon24 commented on Server/Repositories/Filter.cs
> +namespace MathStatisticsProject.Repositories;
перенес в контроллер

2024-05-10 14:27 UTC, semon24 commented on Server/Repositories/HomeworkRepository.cs
> +            context.Homeworks.Add(homework);
Переделал

2024-05-10 15:50 UTC, semon24 commented on Server/Models/Homework.cs
> +        public string WriteMessage
я не знаю) оно до меня было

2024-05-10 15:53 UTC, Cockamamie commented on Server/Models/Homework.cs
> +    [Table("homeWorks")]
EF возьмет имя модели, добавит 's' для множественного числа и так определит нужное имя таблицы

2024-05-10 15:57 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +                foreach (var filterGroup in filter.Groups)
Если пустой, то ничего фильтровать не надо

2024-05-10 15:58 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +                foreach (var filterGroup in filter.Groups)
Пустой => подходят все

2024-05-10 15:59 UTC, Cockamamie commented on Server/Repositories/Filter.cs
> +namespace MathStatisticsProject.Repositories;
Раз используется и там, и там, то правильнее было бы в общее место унести. А сейчас я так же могу написать "Фильтр будет в репозитории использоваться"

2024-05-10 16:15 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +            foreach (var studentHomeworks in JoinStudentHomeworksWithFilter())
И еще. Этот метод про соответствие единственной домашки фильтру. А ты достаешь целый список и исследуешь его

2024-05-10 16:16 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +        private List<dynamic> JoinStudentHomeworksWithFilter()
Асинхронщина

2024-05-11 14:33 UTC, Cockamamie requested changes

2024-05-11 14:33 UTC, Cockamamie commented on Server/Repositories/HomeworkRepository.cs
> +            context.Homeworks.Add(homework);
1. Я в прошлый раз почему-то не оставил коммент про context. Для чего каждый раз новый создается? В конструктор же передается контекст. Для репозиториев, где нужна только одна таблица, можно вообще сразу `DbSet<Model>` передавать
2. Ты поправил не ту строчку, к которой относился комментарий
3. Наоброт синхронно сделал. Короче, должно быть `AddAsync` и `SaveChangesAsync`

2024-05-12 21:53 UTC, merged